apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.project.namespace }}
  name: {{ .Values.project.name }}-db
  labels:
    app: {{ .Values.project.name }}-db
spec:
  selector:
    app: {{ .Values.project.name }}-db
  type: ClusterIP
  ports:
    - port: {{ .Values.postgis.DB_PORT }}
      protocol: TCP
