apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.project.namespace }}
  name: {{ .Values.project.name }}-db-pgadmin
  labels:
    app: {{ .Values.project.name }}-db-pgadmin
spec:
  selector:
    app: {{ .Values.project.name }}-db-pgadmin
  ports:
    - name: "80"
      port: {{ .Values.pgadmin.port | int}}
      targetPort: {{ .Values.pgadmin.targetPort | int }}
