# generated by datamodel-codegen:
#   filename:  https://optimizer-offgridplanner-app.apps2.rl-institut.de/schema/supply/output
#   timestamp: 2025-06-25T16:31:23+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class Model1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scalars: str
    sequences: list[float]


class Model(RootModel[dict[str, Model1] | None]):
    root: dict[str, Model1] | None = None
