x-environment: &global_env
  DB_HOST: db-interactive
  DB_PORT: 5432
  DB_NAME: test
  DB_SUPERADMIN_USERNAME: postgres
  DB_ROLE_API_SERVICE_USERNAME: api_service

  # To be able to use different locales we need to generate OS locales in the postgres container:
  DB_LOCALE: en_US.utf8
  DB_ICU_LOCALE: en-US-x-icu

  SERVICE_OFFGRID_PLANNER_URL: http://host.docker.internal:5001 #https://optimizer-offgridplanner-app.apps2.rl-institut.de

services:
  env-starter:
    image: alpine
    platform: linux/amd64
    restart: no
    healthcheck:
      test: "[ -f /run/secrets/db_superadmin_password ]"
      interval: 1s
      retries: 5
      start_period: 0s
    environment:
      <<: *global_env
    volumes:
      - ../..:/workspaces/potential-minigrid-explorer:cached
      - secrets_volume:/run/secrets
    command:
      - sh
      - -c
      - |
        apk add --no-cache openssl
        echo 'DO NOT DO THIS IN PRODUCTION!: Writing a test only secret for db_role_db_owner_password...'
        echo 'test' > /run/secrets/db_role_db_owner_password
        [ -f /run/secrets/db_role_api_service_password ] || openssl rand -hex 32 > /run/secrets/db_role_api_service_password
        [ -f /run/secrets/db_superadmin_password ] || openssl rand -hex 32 > /run/secrets/db_superadmin_password
        [ -f /run/secrets/api_jwt_encode_key] || openssl rand -hex 32 > /run/secrets/api_jwt_encode_key
        sleep infinity

  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bookworm
    platform: linux/amd64
    depends_on:
      - env-starter
    environment:
      <<: *global_env
    volumes:
      - ../..:/workspaces/potential-minigrid-explorer:cached
      - secrets_volume:/run/secrets:ro
    stdin_open: true # Enables interactive STDIN
    tty: true # Allocates a pseudo-TTY
    command: sleep infinity

  db-interactive:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: postgres-interactive-testing
    restart: unless-stopped
    depends_on:
      env-starter:
        condition: service_healthy
    environment:
      <<: *global_env
      POSTGRES_USER: ${DB_SUPERADMIN_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_superadmin_password
    volumes:
      - secrets_volume:/run/secrets:ro
      - ../../database/postgres-setup.d:/docker-entrypoint-initdb.d:ro
      - db_interactive_volume:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - db-interactive
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80" # Access via localhost:8080 on host machine
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ../../tests/pgadmin_config/servers.json:/pgadmin4/servers.json:ro

volumes:
  secrets_volume:
    name: dec_potential_secrets

  db_interactive_volume:
    name: dec_potential_db_interactive

  pgadmin_data:
    name: dec_potential_pgadmin_data
